schemas = {
    'installations': [
        {'name': 'application_id', 'type': 'STRING', 'description': 'Уникальный числовой идентификатор приложения в AppMetrica.'},
        {'name': 'click_datetime', 'type': 'DATETIME', 'description': 'Дата и время клика.'},
        {'name': 'click_id', 'type': 'STRING', 'description': 'Идентификатор клика или \'\' (пустая строка, если недоступен).'},
        {'name': 'click_ipv6', 'type': 'STRING', 'description': 'IP-адрес в момент клика в формате IPv6.'},
        {'name': 'click_timestamp', 'type': 'INTEGER', 'description': 'Время клика в формате UNIX-time в секундах.'},
        {'name': 'click_url_parameters', 'type': 'STRING', 'description': 'Параметры, как они представлены в ссылке.'},
        {'name': 'click_user_agent', 'type': 'STRING', 'description': 'User-agent клика.'},
        {'name': 'profile_id', 'type': 'STRING', 'description': 'Идентификатор пользовательского профиля.'},
        {'name': 'publisher_id', 'type': 'STRING', 'description': 'ID партнера в AppMetrica.'},
        {'name': 'publisher_name', 'type': 'STRING', 'description': 'Название партнера AppMetrica.'},
        {'name': 'tracker_name', 'type': 'STRING', 'description': 'Название трекера, который добавляется в интерфейсе AppMetrica.'},
        {'name': 'tracking_id', 'type': 'STRING', 'description': 'ID трекера в AppMetrica.'},
        {'name': 'install_datetime', 'type': 'DATETIME', 'description': 'Дата и время установки.'},
        {'name': 'install_timestamp', 'type': 'INTEGER', 'description': 'Время установки в формате UNIX-time в секундах.'},
        {'name': 'install_ipv6', 'type': 'STRING', 'description': 'IP-адрес в момент установки в формате IPv6.'},
        {'name': 'install_receive_datetime', 'type': 'DATETIME', 'description': 'Дата и время получения сервером события об установке.'},
        {'name': 'install_receive_timestamp', 'type': 'INTEGER', 'description': 'Время получения сервером события об установке в формате UNIX-time.'},
        {'name': 'is_reattribution', 'type': 'BOOL', 'description': 'Признак реатрибутирования установки новому источнику.'},
        {'name': 'is_reinstallation', 'type': 'BOOL', 'description': 'Признак переустановки приложения.'},
        {'name': 'match_type', 'type': 'STRING', 'description': 'Способ атрибуции.'},
        {'name': 'appmetrica_device_id', 'type': 'STRING', 'description': 'Уникальный идентификатор устройства, который устанавливает AppMetrica.'},
        {'name': 'city', 'type': 'STRING', 'description': 'Название города на английском языке, где был произведен клик.'},
        {'name': 'connection_type', 'type': 'STRING', 'description': 'Тип подключения устройства.'},
        {'name': 'country_iso_code', 'type': 'STRING', 'description': 'ISO-код страны.'},
        {'name': 'device_locale', 'type': 'STRING', 'description': 'Язык интерфейса устройства.'},
        {'name': 'device_manufacturer', 'type': 'STRING', 'description': 'Производитель устройства.'},
        {'name': 'device_model', 'type': 'STRING', 'description': 'Модель устройства.'},
        {'name': 'device_type', 'type': 'STRING', 'description': 'Тип устройства.'},
        {'name': 'google_aid', 'type': 'STRING', 'description': 'Google AID устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifa', 'type': 'STRING', 'description': 'IFA устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifv', 'type': 'STRING', 'description': 'IFV для приложения в формате, в котором получен от устройства.'},
        {'name': 'windows_aid', 'type': 'STRING', 'description': 'Windows AID устройства в формате, в котором получен от устройства.'},
        {'name': 'mcc', 'type': 'INTEGER', 'description': 'Мобильный код страны.'},
        {'name': 'mnc', 'type': 'INTEGER', 'description': 'Код мобильной сети.'},
        {'name': 'operator_name', 'type': 'STRING', 'description': 'Имя оператора сотовой связи.'},
        {'name': 'os_name', 'type': 'STRING', 'description': 'Операционная система на устройстве пользователя.'},
        {'name': 'os_version', 'type': 'STRING', 'description': 'Версия операционной системы на устройстве пользователя.'},
        {'name': 'app_package_name', 'type': 'STRING', 'description': 'Имя пакета для Android или Bundle ID для iOS.'},
        {'name': 'app_version_name', 'type': 'STRING', 'description': 'Версия приложения в виде, как указана разработчиком.'},
    ],
    'events': [
        {'name': 'event_datetime', 'type': 'DATETIME', 'description': 'Дата и время события.'},
        {'name': 'event_json', 'type': 'STRING', 'description': 'Атрибуты события, сериализованные в JSON.'},
        {'name': 'event_name', 'type': 'STRING', 'description': 'Имя события (как передано в SDK).'},
        {'name': 'event_receive_datetime', 'type': 'DATETIME', 'description': 'Дата и время получения сервером события.'},
        {'name': 'event_receive_timestamp', 'type': 'INTEGER', 'description': 'Время получения сервером события в формате UNIX-time.'},
        {'name': 'event_timestamp', 'type': 'INTEGER', 'description': 'Время события в формате UNIX-time.'},
        {'name': 'session_id', 'type': 'STRING', 'description': 'Идентификатор сессии.'},
        {'name': 'installation_id', 'type': 'STRING', 'description': 'Идентификатор установки.'},
        {'name': 'appmetrica_device_id', 'type': 'STRING', 'description': 'Уникальный идентификатор устройства, который устанавливает AppMetrica.'},
        {'name': 'city', 'type': 'STRING', 'description': 'Название города на английском языке, где был произведен клик.'},
        {'name': 'connection_type', 'type': 'STRING', 'description': 'Тип подключения устройства.'},
        {'name': 'country_iso_code', 'type': 'STRING', 'description': 'ISO-код страны.'},
        {'name': 'device_ipv6', 'type': 'STRING', 'description': 'IP-адрес в момент совершения события в формате IPv6.'},
        {'name': 'device_locale', 'type': 'STRING', 'description': 'Язык интерфейса устройства.'},
        {'name': 'device_manufacturer', 'type': 'STRING', 'description': 'Производитель устройства.'},
        {'name': 'device_model', 'type': 'STRING', 'description': 'Модель устройства.'},
        {'name': 'device_type', 'type': 'STRING', 'description': 'Тип устройства.'},
        {'name': 'google_aid', 'type': 'STRING', 'description': 'Google AID устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifa', 'type': 'STRING', 'description': 'IFA устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifv', 'type': 'STRING', 'description': 'IFV для приложения в формате, в котором получен от устройства.'},
        {'name': 'mcc', 'type': 'INTEGER', 'description': 'Мобильный код страны.'},
        {'name': 'mnc', 'type': 'INTEGER', 'description': 'Код мобильной сети.'},
        {'name': 'operator_name', 'type': 'STRING', 'description': 'Имя оператора сотовой связи.'},
        {'name': 'original_device_model', 'type': 'STRING', 'description': 'Заводская модель устройства.'},
        {'name': 'os_name', 'type': 'STRING', 'description': 'Операционная система на устройстве пользователя.'},
        {'name': 'os_version', 'type': 'STRING', 'description': 'Версия операционной системы на устройстве пользователя.'},
        {'name': 'profile_id', 'type': 'STRING', 'description': 'Идентификатор пользовательского профиля.'},
        {'name': 'windows_aid', 'type': 'STRING', 'description': 'Windows AID устройства в формате, в котором получен от устройства.'},
        {'name': 'app_build_number', 'type': 'INTEGER', 'description': 'Номер сборки приложения.'},
        {'name': 'app_package_name', 'type': 'STRING', 'description': 'Имя пакета для Android или Bundle ID для iOS.'},
        {'name': 'app_version_name', 'type': 'STRING', 'description': 'Версия приложения в виде, как указана разработчиком.'},
        {'name': 'application_id', 'type': 'STRING', 'description': 'Уникальный числовой идентификатор приложения в AppMetrica.'},
    ],
    'revenue_events': [
        {'name': 'revenue_quantity', 'type': 'INTEGER', 'description': 'Количество покупок (купленных товаров).'},
        {'name': 'revenue_price', 'type': 'STRING', 'description': 'Стоимость. Может быть отрицательной (например, для возврата).'},
        {'name': 'revenue_currency', 'type': 'STRING', 'description': 'од валюты покупки в формате ISO 4217.'},
        {'name': 'revenue_product_id', 'type': 'STRING', 'description': 'Идентификатор товара.'},
        {'name': 'revenue_order_id', 'type': 'STRING', 'description': 'Идентификатор заказа.'},
        {'name': 'revenue_order_id_source', 'type': 'STRING', 'description': 'Источник идентификатора заказа.'},
        {'name': 'is_revenue_verified', 'type': 'STRING', 'description': 'Признак верификации покупки в магазине.'},
        {'name': 'event_datetime', 'type': 'DATETIME', 'description': 'Дата и время события'},
        {'name': 'event_name', 'type': 'STRING', 'description': 'Имя события (как передано в SDK).'},
        {'name': 'event_receive_datetime', 'type': 'DATETIME', 'description': 'Дата и время получения сервером события.'},
        {'name': 'event_receive_timestamp', 'type': 'INTEGER', 'description': 'Время получения сервером события в формате UNIX-time.'},
        {'name': 'event_timestamp', 'type': 'INTEGER', 'description': 'Время события в формате UNIX-time.'},
        {'name': 'session_id', 'type': 'STRING', 'description': 'Идентификатор сессии.'},
        {'name': 'installation_id', 'type': 'STRING', 'description': 'Идентификатор установки.'},
        {'name': 'android_id', 'type': 'STRING', 'description': 'Идентификатор Android.'},
        {'name': 'appmetrica_device_id', 'type': 'STRING', 'description': 'Уникальный идентификатор устройства, который устанавливает AppMetrica.'},
        {'name': 'appmetrica_sdk_version', 'type': 'STRING', 'description': 'Версия AppMetrica SDK.'},
        {'name': 'city', 'type': 'STRING', 'description': 'Название города на английском языке, где был произведен клик.'},
        {'name': 'connection_type', 'type': 'STRING', 'description': 'Тип подключения устройства.'},
        {'name': 'country_iso_code', 'type': 'STRING', 'description': 'ISO-код страны.'},
        {'name': 'device_ipv6', 'type': 'STRING', 'description': 'IP-адрес в момент совершения события в формате IPv6.'},
        {'name': 'device_locale', 'type': 'STRING', 'description': 'Язык интерфейса устройства.'},
        {'name': 'device_manufacturer', 'type': 'STRING', 'description': 'Производитель устройства.'},
        {'name': 'device_model', 'type': 'STRING', 'description': 'Модель устройства.'},
        {'name': 'event_datetime', 'type': 'DATETIME', 'description': 'Дата и время события'},
        {'name': 'google_aid', 'type': 'STRING', 'description': 'Google AID устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifa', 'type': 'STRING', 'description': 'IFA устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifv', 'type': 'STRING', 'description': 'IFV для приложения в формате, в котором получен от устройства.'},
        {'name': 'mcc', 'type': 'INTEGER', 'description': 'Мобильный код страны.'},
        {'name': 'mnc', 'type': 'INTEGER', 'description': 'Код мобильной сети.'},
        {'name': 'operator_name', 'type': 'STRING', 'description': 'Имя оператора сотовой связи.'},
        {'name': 'original_device_model', 'type': 'STRING', 'description': 'Заводская модель устройства.'},
        {'name': 'os_version', 'type': 'STRING', 'description': 'Версия операционной системы на устройстве пользователя.'},
        {'name': 'profile_id', 'type': 'STRING', 'description': 'Идентификатор пользовательского профиля.'},
        {'name': 'windows_aid', 'type': 'STRING', 'description': 'Windows AID устройства в формате, в котором получен от устройства.'},
        {'name': 'app_build_number', 'type': 'INTEGER', 'description': 'Номер сборки приложения.'},
        {'name': 'app_package_name', 'type': 'STRING', 'description': 'Имя пакета для Android или Bundle ID для iOS.'},
        {'name': 'app_version_name', 'type': 'STRING', 'description': 'Версия приложения в виде, как указана разработчиком.'},
    ],
    'profiles': [
        {'name': 'profile_id', 'type': 'STRING', 'description': 'Идентификатор пользовательского профиля.'},
        {'name': 'appmetrica_gender', 'type': 'STRING', 'description': 'Пол.'},
        {'name': 'appmetrica_birth_date', 'type': 'DATE', 'description': 'Возраст.'},
        {'name': 'appmetrica_notifications_enabled', 'type': 'BOOL', 'description': 'Push разрешены.'},
        {'name': 'appmetrica_name', 'type': 'STRING', 'description': 'Имя.'},
        {'name': 'appmetrica_crashes', 'type': 'INTEGER', 'description': 'Количество крэшей.'},
        {'name': 'appmetrica_errors', 'type': 'INTEGER', 'description': 'Количество ошибок.'},
        {'name': 'appmetrica_first_session_date', 'type': 'DATE', 'description': 'Дата начала первой сессии.'},
        {'name': 'appmetrica_last_start_date', 'type': 'DATE', 'description': 'Дата последнего запуска приложения.'},
        {'name': 'appmetrica_push_opens', 'type': 'INTEGER', 'description': 'Количество открытых push-уведомлений.'},
        {'name': 'appmetrica_push_send_count', 'type': 'INTEGER', 'description': 'Количество отправленных push-уведомлений.'},
        {'name': 'appmetrica_sdk_version', 'type': 'STRING', 'description': 'Версия AppMetrica SDK.'},
        {'name': 'appmetrica_sessions', 'type': 'INTEGER', 'description': 'Количество сессий.'},
        {'name': 'android_id', 'type': 'STRING', 'description': 'Идентификатор Android.'},
        {'name': 'appmetrica_device_id', 'type': 'STRING', 'description': 'Уникальный идентификатор устройства, который устанавливает AppMetrica.'},
        {'name': 'city', 'type': 'STRING', 'description': 'Название города на английском языке, где был произведен клик.'},
        {'name': 'connection_type', 'type': 'STRING', 'description': 'Тип подключения устройства.'},
        {'name': 'country_iso_code', 'type': 'STRING', 'description': 'ISO-код страны.'},
        {'name': 'device_manufacturer', 'type': 'STRING', 'description': 'Производитель устройства.'},
        {'name': 'device_model', 'type': 'STRING', 'description': 'Модель устройства.'},
        {'name': 'device_type', 'type': 'STRING', 'description': 'Тип устройства.'},
        {'name': 'google_aid', 'type': 'STRING', 'description': 'Google AID устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifa', 'type': 'STRING', 'description': 'IFA устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifv', 'type': 'STRING', 'description': 'IFV для приложения в формате, в котором получен от устройства.'},
        {'name': 'mcc', 'type': 'STRING', 'description': 'Мобильный код страны.'},
        {'name': 'mnc', 'type': 'STRING', 'description': 'Код мобильной сети.'},
        {'name': 'operator_name', 'type': 'STRING', 'description': 'Имя оператора сотовой связи.'},
        {'name': 'os_name', 'type': 'STRING', 'description': 'Операционная система на устройстве пользователя.'},
        {'name': 'os_version', 'type': 'STRING', 'description': 'Версия операционной системы на устройстве пользователя.'},
        {'name': 'windows_aid', 'type': 'STRING', 'description': 'Windows AID устройства в формате, в котором получен от устройства.'},
        {'name': 'app_build_number', 'type': 'INTEGER', 'description': 'Номер сборки приложения.'},
        {'name': 'app_framework', 'type': 'INTEGER', 'description': 'Тип фреймворка.'},
        {'name': 'app_package_name', 'type': 'STRING', 'description': 'Имя пакета для Android или Bundle ID для iOS.'},
        {'name': 'app_version_name', 'type': 'STRING', 'description': 'Версия приложения в виде, как указана разработчиком.'},
    ],
    'sessions_starts': [
        {'name': 'session_id', 'type': 'STRING', 'description': 'Идентификатор сессии.'},
        {'name': 'session_start_datetime', 'type': 'DATETIME', 'description': 'Дата и время начала сессии.'},
        {'name': 'session_start_receive_datetime', 'type': 'DATETIME', 'description': 'Время получения сервером сообщения о начале сессии.'},
        {'name': 'session_start_receive_timestamp', 'type': 'INTEGER', 'description': 'Время получения сервером сообщения о начале сессии в формате UNIX-time.'},
        {'name': 'session_start_timestamp', 'type': 'INTEGER', 'description': 'Время начала сессии в формате UNIX-time.'},
        {'name': 'appmetrica_device_id', 'type': 'STRING', 'description': 'Уникальный идентификатор устройства, который устанавливает AppMetrica.'},
        {'name': 'city', 'type': 'STRING', 'description': 'Название города на английском языке, где был произведен клик.'},
        {'name': 'connection_type', 'type': 'STRING', 'description': 'Тип подключения устройства.'},
        {'name': 'country_iso_code', 'type': 'STRING', 'description': 'ISO-код страны.'},
        {'name': 'device_ipv6', 'type': 'STRING', 'description': 'IP-адрес в момент совершения события в формате IPv6.'},
        {'name': 'device_locale', 'type': 'STRING', 'description': 'Язык интерфейса устройства.'},
        {'name': 'device_manufacturer', 'type': 'STRING', 'description': 'Производитель устройства.'},
        {'name': 'device_model', 'type': 'STRING', 'description': 'Модель устройства.'},
        {'name': 'device_type', 'type': 'STRING', 'description': 'Тип устройства.'},
        {'name': 'google_aid', 'type': 'STRING', 'description': 'Google AID устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifa', 'type': 'STRING', 'description': 'IFA устройства в формате, в котором получен от устройства.'},
        {'name': 'ios_ifv', 'type': 'STRING', 'description': 'IFV для приложения в формате, в котором получен от устройства.'},
        {'name': 'mcc', 'type': 'STRING', 'description': 'Мобильный код страны.'},
        {'name': 'mnc', 'type': 'STRING', 'description': 'Код мобильной сети.'},
        {'name': 'operator_name', 'type': 'STRING', 'description': 'Имя оператора сотовой связи.'},
        {'name': 'original_device_model', 'type': 'STRING', 'description': 'Заводская модель устройства.'},
        {'name': 'os_name', 'type': 'STRING', 'description': 'Операционная система на устройстве пользователя.'},
        {'name': 'os_version', 'type': 'STRING', 'description': 'Версия операционной системы на устройстве пользователя.'},
        {'name': 'profile_id', 'type': 'STRING', 'description': 'Идентификатор пользовательского профиля.'},
        {'name': 'windows_aid', 'type': 'STRING', 'description': 'Windows AID устройства в формате, в котором получен от устройства.'},
        {'name': 'app_build_number', 'type': 'INTEGER', 'description': 'Номер сборки приложения.'},
        {'name': 'app_package_name', 'type': 'STRING', 'description': 'Имя пакета для Android или Bundle ID для iOS.'},
        {'name': 'app_version_name', 'type': 'STRING', 'description': 'Версия приложения в виде, как указана разработчиком.'},
        {'name': 'application_id', 'type': 'STRING', 'description': 'Уникальный числовой идентификатор приложения в AppMetrica.'},
    ]
}
